// <auto-generated />
using Commander.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Commander.Migrations
{
  [DbContext(typeof(CommandContext))]
  partial class CommanderContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .UseIdentityColumns()
          .HasAnnotation("Relational:MaxIdentifierLength", 128)
          .HasAnnotation("ProductVersion", "5.0.0");

      modelBuilder.Entity("Commander.Models.Command", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int")
                      .UseIdentityColumn();

            b.Property<string>("HowTo")
                      .IsRequired()
                      .HasMaxLength(400)
                      .HasColumnType("nvarchar(400)");

            b.Property<string>("Line")
                      .IsRequired()
                      .HasMaxLength(300)
                      .HasColumnType("nvarchar(300)");

            b.Property<string>("Plataform")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("nvarchar(100)");

            b.HasKey("Id");

            b.ToTable("Commands");
          });
#pragma warning restore 612, 618
    }
  }
}
